### PR TITLE
fix: removed UID field from plant doctype

### PR DESCRIPTION
**Pull request by meshramsaroj**
Task **Link:** https://bloomstack.com/desk#Form/Task/TASK-2021-00354

**GIF and screenshot:**
removed UID field from plant doctype
removed statistic section from plant doctype and added four new dates filed instead of it.
image

removed destroyed count  and changes resion field type from destroyed plan log of plant doctype
distroyed_plant-log

made changes in destroyed plan log of plant batch doctype
Screenshot from 2021-11-11 19-19-49

Updated plant batch's untracked count and tracked when a plant is created.
update_tracked_and_untracked_count

### CODE REVIEW

**Comment by neilLasrado** [comment]
@meshramsaroj why did you remove UID from Plant doctype?

**Comment by meshramsaroj** [comment]
> @meshramsaroj why did you remove UID from Plant doctype?

@neilLasrado  because it's mentioned under the task description, that's why I removed this field.
Should I have to hide this field?

**Comment by meshramsaroj** [comment]
> > @meshramsaroj why did you remove UID from Plant doctype?
> 
> @neilLasrado because it's mentioned under the task description, that's why I removed this field. Should I have to hide this field?

@neilLasrado Please review this PR

**Review by neilLasrado — APPROVED** [review]

**Comment by neilLasrado** [comment]
@meshramsaroj This PR is good. I was confused with UID & the plant tag. UID Seems to be a duplicate field for plant tag.

**Comment by Anurag810** [comment]
@meshramsaroj please fix the sider.

**Review by sahil28297 — APPROVED** [review]

**Pull request merged**
