### PR TITLE
fix: add a field to harvest plant

### PR DESCRIPTION
**Pull request by nmimsnikhil**
ref: https://app.asana.com/0/1192407899754728/1198561317090455

Total harvest

### CODE REVIEW

**Review by vishdha — APPROVED** [review]

**Review by hrwX — APPROVED** [review]

**Comment by hrwX** [comment]
@nmimsnikhil please resolve the conflicts

**Review by neilLasrado — CHANGES_REQUESTED** [review]
Can you please move the harvest weight to the list view of the child table? Make the total harvest weight read-only

**Review by sahil28297 — APPROVED** [review]

**Comment by sahil28297** [comment]
@nmimsnikhil plz fix the conflicts and update the PR as Neil suggested

**Comment by nmimsnikhil** [comment]
@neilLasrado I have move 'Harvest Weight' to list view but for displaying it in list view i have removed 'strain' from list view.

**Comment by neilLasrado** [comment]
@nmimsnikhil can you fix the merge conflicts and push?

**Review by neilLasrado — APPROVED** [review]

**Pull request merged**
