### PR TITLE
fix: removed category from strain doctype

### PR DESCRIPTION
**Pull request by meshramsaroj**
**Task Link:** https://bloomstack.com/desk#Form/Task/TASK-2021-00351

**Screenshot:**

- Added validation for Indica & Sativa should be 100 %

validation

- Removed category from strain doctype
Before
image

After
image

- Moved company to the bottom of the form of strain doctype
Before
image

After
image

-  Customer provided item is moved below Allow Alternate Item of BOM Item table.
Before
image

After
image

**Bllomstack_core PR:** https://github.com/Bloomstack/bloomstack_core/pull/757

### CODE REVIEW

**Comment by MyuddinKhatri** [comment]
@meshramsaroj  please add specific PR title.

**Comment by sahil28297** [comment]
@meshramsaroj this was merging of apps activity as far as I remember, if it is then it should go in sep-sprint-1 branch. @MyuddinKhatri please confirm

**Comment by MyuddinKhatri** [comment]
> @meshramsaroj this was merging of apps activity as far as I remember, if it is then it should go in sep-sprint-1 branch. @MyuddinKhatri please confirm

Yes this should go in sep-sprint-1 @meshramsaroj

**Review by neilLasrado — DISMISSED** [review]

**Comment by meshramsaroj** [comment]
PR is already created for this changes https://github.com/Bloomstack/erpnext/pull/1807

**Pull request closed without merging**
