### PR TITLE
feat: run-parallel test

### PR DESCRIPTION
**Pull request by vishdha**
depends on :https://github.com/Bloomstack/frappe/pull/789

### CODE REVIEW

**Comment by neilLasrado** [comment]
@vishdha whats going on with this?

**Comment by vishdha** [comment]
this feature will brings down testing time to 10 min. but for this we need orachestor account. @sahil will need to take action wheather we go with orachestor or not

**Comment by vishdha** [comment]
this feature will brings down testing time to 10 min. but for this we need orachestor account. @sahil will need to take action wheather we go with orachestor or not

**Comment by vishdha** [comment]
this feature will brings down testing time to 10 min. but for this we need orachestor account. @sahil will need to take action wheather we go with orachestor or not

**Comment by neilLasrado** [comment]
@sahil28297 can you please take care of this today? send me and Aloke whats the Estimated cost for this service is. lets close this soon, having lower testing time is great for us!

**Comment by neilLasrado** [comment]
@sahil28297 please look into this

**Pull request closed without merging**
