### PR TITLE
Validate if QI against transactions are submitted or not

### PR DESCRIPTION
**Pull request by Alchez**
Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

### CODE REVIEW

**Comment by vjFaLk** [comment]
Wasn't there a PR on upstream that did the same thing? What happened to it?

**Comment by Alchez** [comment]
It's still open: https://github.com/frappe/erpnext/pull/16289

**Comment by vjFaLk** [comment]
Would you say that your implementation is better? In that case you should mention it there and rather that PR not be merged.

**Comment by Alchez** [comment]
Just reviewed it. I think their implementation is actually better, in that they're also incorporating tests, and adding checks for "Rejected" QIs. Let's just close this, and pull that one when it's merged.

**Comment by vjFaLk** [comment]
Let's help them get it merged, are the tests failing or is it just travis blowing up?

**Comment by Alchez** [comment]
It's failing at unrelated stuff, yeah. Also, that guy needs to fix Nabin's requested changes, and then it's good to go.

**Pull request closed without merging**
