### PR TITLE
fix: added a sales order field on purchase order form

### PR DESCRIPTION
**Pull request by nehasacher143**
Task: https://bloomstack.com/desk#Form/Task/TASK-2021-00212
GIF:
Peek 2021-08-17 19-30

P.S. Once this is merged and deployed then only the value can be added to the Print Format

### CODE REVIEW

**Review by vishdha — APPROVED** [review]

**Review by neilLasrado — CHANGES_REQUESTED** [review]
Sales Order link already exists in the Purchase Order line item

**Comment by neilLasrado** [comment]
Screenshot 2021-08-18 at 3 49 44 PM

**Comment by sahil28297** [comment]
@nehasacher143 any updates on this?

**Comment by nehasacher143** [comment]
@sahil28297  @vishdha This PR is not required now.

**Pull request closed without merging**
