### PR TITLE
feat: Minutes of Meeting Feature Introduce for Project Module

### PR DESCRIPTION
**Pull request by vishdha**
Peek 2021-11-01 10-38

### CODE REVIEW

**Review by neilLasrado — CHANGES_REQUESTED** [review]
The doctype should be called 'Meeting'. & Minutes should be a section in the doctype

**Comment by neilLasrado** [comment]
Also, Agenda & Minutes should be text fields, not in a Child table.

**Comment by vishdha** [comment]
> The doctype should be called 'Meeting'. & Minutes should be a section in the doctype

Yes Minutes is a section in doctype and I will change name to meeting

**Comment by vishdha** [comment]
> Also, Agenda & Minutes should be text fields, not in a Child table.

I assume the use case where one Meeting have multiple agenda that's why added into child table and each agenda may have some minutes and we can create task against that thats why moved agenda and minutes to child table

**Comment by neilLasrado** [comment]
@vishdha Each meeting should have a single Agenda & Minutes

What you can do is Call the Section 'Meeting Agenda', inside it, you can have a child table with 'Agenda Points' & 'Decisions' & 'Action Pointers'

'Minutes of the Meeting' can be a print format that combines all this info into one. 

check- https://www.meetingminutes.com/meeting-minutes-formats

**Pull request closed without merging**
