### PR TITLE
feat: change delivery workflow to include packing slips

### PR DESCRIPTION
**Pull request by Alchez**
**Ref:** [TASK-2019-00035](https://digithinkit.global/desk#Form/Task/TASK-2019-00035)

Stock Entry logic moved from https://github.com/DigiThinkIT/bloomstack_core/pull/102.

<hr>

**Bloomstack Checklist:**

**Sales Order:**
- [x] Be able to create Packing Slips from Sales Orders.

**Packing Slip:**
- [x] Make Packing Slip against a Sales Order instead of Delivery Note.
- [x] On submit of Packing Slip, create a draft Delivery Note with all the packed items.
- [x] On auto-creation of Stock Entry after submit of Packing Slip, set references in the Stock Entry against SO / Packing Slip.
- [ ] Update status of SO as follows:
  - [ ] From "To Deliver" to "To Pack" if a draft Packing Slip is created,
  - [ ] From "To Pack" to "To Deliver" if Packing Slip is submitted,
  - [ ] No change if Packing Slip is cancelled.

**Delivery Note:**
- [x] Retrieve items from Packing Slip(s) made against any linked Sales Orders.
- [x] Modify creation of DN from multiple SOs - the current "Get Items From" dialog lets you select SOs for multiple Customers and then creates the DN against the last Customer; maybe only show the prompt when a Customer is selected.

**Delivery Trip:**
- [x] Create Delivery Trip only from both draft and submitted DNs (with or without Packing Slips).

<hr>

**Driver App Checklist:**

**Delivery Trip:**
- Once the driver starts the delivery, auto-submit all linked DNs.
- Once the driver delivers packages for a customer, auto-create and submit a Sales Invoice, and send it to the customer.
  - Allow printing of the invoice manually, since drivers may carry a home printer with them
- Update timesheets based on driver activity (whether they're scanning items or out for delivery).

<hr>

**Screenshots / GIFs:**

**Mockup:**

image

### CODE REVIEW

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 6
           

Clones added
============
- erpnext/stock/doctype/packing_slip/test_packing_slip.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/erpnext/erpnext/pullRequest?prid=4542355&bid=15286688)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 12
- Added 11
           

Complexity decreasing per file
==============================
+ erpnext/stock/doctype/packing_slip/packing_slip.js  -1
         

Clones added
============
- erpnext/stock/doctype/packing_slip/test_packing_slip.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/erpnext/erpnext/pullRequest?prid=4542355&bid=15286688)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 13
- Added 11
           

Complexity decreasing per file
==============================
+ erpnext/stock/doctype/packing_slip/packing_slip.js  -4
         

Clones added
============
- erpnext/stock/doctype/packing_slip/test_packing_slip.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/erpnext/erpnext/pullRequest?prid=4542355&bid=15286688)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 13
- Added 10
           

Complexity increasing per file
==============================
- erpnext/stock/doctype/packing_slip/packing_slip_dashboard.py  1
         

Complexity decreasing per file
==============================
+ erpnext/stock/doctype/packing_slip/packing_slip.py  -1
+ erpnext/stock/doctype/packing_slip/packing_slip.js  -4
         

Clones added
============
- erpnext/stock/doctype/packing_slip/test_packing_slip.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/erpnext/erpnext/pullRequest?prid=4542355&bid=15286688)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 13
- Added 6
           

Complexity increasing per file
==============================
- erpnext/stock/doctype/packing_slip/packing_slip_dashboard.py  1
         

Complexity decreasing per file
==============================
+ erpnext/stock/doctype/packing_slip/packing_slip.js  -4
         

Clones added
============
- erpnext/stock/doctype/packing_slip/test_packing_slip.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/erpnext/erpnext/pullRequest?prid=4542355&bid=15286688)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 13
- Added 6
           

Complexity increasing per file
==============================
- erpnext/stock/doctype/packing_slip/packing_slip_dashboard.py  1
         

Complexity decreasing per file
==============================
+ erpnext/stock/doctype/packing_slip/packing_slip.js  -4
         

Clones added
============
- erpnext/stock/doctype/packing_slip/test_packing_slip.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/erpnext/erpnext/pullRequest?prid=4542355&bid=15286688)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 13
- Added 8
           

Complexity increasing per file
==============================
- erpnext/stock/doctype/packing_slip/packing_slip_dashboard.py  1
         

Complexity decreasing per file
==============================
+ erpnext/stock/doctype/packing_slip/packing_slip.js  -4
         

Clones added
============
- erpnext/stock/doctype/packing_slip/test_packing_slip.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/erpnext/erpnext/pullRequest?prid=4542355&bid=15286688)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 13
- Added 6
           

Complexity increasing per file
==============================
- erpnext/stock/doctype/packing_slip/packing_slip_dashboard.py  1
         

Complexity decreasing per file
==============================
+ erpnext/stock/doctype/packing_slip/packing_slip.js  -4
         

Clones added
============
- erpnext/stock/doctype/packing_slip/test_packing_slip.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/erpnext/erpnext/pullRequest?prid=4542355&bid=15286688)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 14
- Added 7
           

Complexity increasing per file
==============================
- erpnext/stock/doctype/packing_slip/packing_slip_dashboard.py  1
         

Complexity decreasing per file
==============================
+ erpnext/stock/doctype/packing_slip/packing_slip.js  -4
         

Clones added
============
- erpnext/stock/doctype/packing_slip/test_packing_slip.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/erpnext/erpnext/pullRequest?prid=4542355&bid=15286688)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 14
- Added 8
           

Complexity increasing per file
==============================
- erpnext/stock/doctype/packing_slip/packing_slip_dashboard.py  1
         

Complexity decreasing per file
==============================
+ erpnext/stock/doctype/packing_slip/packing_slip.js  -2
         

Clones added
============
- erpnext/stock/doctype/packing_slip/test_packing_slip.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/erpnext/erpnext/pullRequest?prid=4542355&bid=15286688)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 14
- Added 6
           

Complexity increasing per file
==============================
- erpnext/stock/doctype/packing_slip/packing_slip_dashboard.py  1
         

Complexity decreasing per file
==============================
+ erpnext/stock/doctype/packing_slip/packing_slip.js  -2
         

Clones added
============
- erpnext/stock/doctype/packing_slip/test_packing_slip.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/erpnext/erpnext/pullRequest?prid=4542355&bid=15286688)

**Comment by Alchez** [comment]
Closing until this comes up as a request again.

**Pull request closed without merging**
