### PR TITLE
[staging] Add recent changes to new branch

### PR DESCRIPTION
**Pull request by Alchez**

### CODE REVIEW

**Comment by DeveloperMetal** [comment]
@Alchez We still need to setup a server to test this right?
Will get with Sahil to prop a test server for this and future ci/cd stuff

**Comment by Alchez** [comment]
@DeveloperMetal, yeah, was just waiting for tests to pass. Seems like py3.6 is good to go, I've rerun the patch test for 3.6, let's see how that one goes.

**Comment by DeveloperMetal** [comment]
@Alchez Hey, so only the patch tests are failing on 3.6

I don't think we should care for any of the old 2.7 anyways. We should strip out those from the test.
What's stopping us from syncing things back with this pr and re-organizing our branches as we talked about?

**Comment by DeveloperMetal** [comment]
@neilLasrado @Alchez Hey guys when you get a chance can you check the tests looks like the last few merges broke something on delivery dates

**Pull request merged**
