### PR TITLE
chore(print): Remove unnecessary fields from Purchase Cycle document prints

### PR DESCRIPTION
**Pull request by Alchez**
**Ref:** [TASK-2019-00345](https://digithinkit.global/desk#Form/Task/TASK-2019-00345)

<hr>

**ToDo:**
- Any additional changes discussed in the Task document

**Changes:**
- Purchase Invoice
  - Hide "Status"
  - Hide "Print Language"
- Purchase Invoice Item
  - Hide "Include Exploded Items"
  - Show "Purchase Order"
- Purchase Order Item
  - Hide "Include Exploded Items"
  - Hide "Last Purchase Rate"
- Purchase Receipt Item
  - Hide "Include Exploded Items"
  - Show "Purchase Order"

### CODE REVIEW

**Comment by vjFaLk** [comment]
This generic enough to upstream? Else why not just have this as a customization in Bloomstack Core?

**Comment by Alchez** [comment]
Yeah, this is pretty generic. I'm gonna hold off making it upstream until we have the complete list of changes that can go there (document available in the linked Task).

**Comment by vjFaLk** [comment]
Pls fix conflicts, thenks

**Comment by Alchez** [comment]
Made upstream to [develop](https://github.com/frappe/erpnext/pull/19101).

**Review by vjFaLk — APPROVED** [review]

**Pull request merged**
