### PR TITLE
fix: Chart of account importer UX improved

### PR DESCRIPTION
**Pull request by vishdha**
Before:
Chart of Accounts Importer

After:
Chart of Accounts Importer (1)

### CODE REVIEW

**Comment by Alchez** [comment]
@vishdha, this looks good, but can you add the names to all the throw messages in that file? Let's just improve it entirely.

Also, let's highlight the account numbers. You can do `self.name.bold()`, which will add a `<b>` tag to the text in the throw.

**Comment by vishdha** [comment]
@Alchez  Added the change

**Comment by vishdha** [comment]
@Alchez Root validation is on account not on chart of account importer so getting of all frappe.throw is kind of tricky

**Review by Alchez — APPROVED** [review]

**Comment by vishdha** [comment]
hotfix: https://github.com/frappe/erpnext/pull/21266
develop: https://github.com/frappe/erpnext/pull/21265

**Pull request merged**
