### PR TITLE
fix: added a Reason for Return field for each items

### PR DESCRIPTION
**Pull request by nmimsnikhil**
Added a field "Reason for Return" when creating Sales Return of Delivery Note for each items.

Before:
delivery_note_task

After
reason_for_return

### CODE REVIEW

**Comment by DeveloperMetal** [comment]
Hey quick question. Are we sending these changes upstream? I keep seeing prs to our core ERPNext fork and I don’t believe we should be doing this if we are not going to do a or upstream and if not should these not be customized form fields instead? @Alchez @nmimsnikhil 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Alchez** [comment]
@forellana-digithinkit, yeah, we actively send all Frappe and ERPNext PRs upstream. If it counts as a customization, we only send it to bloomstack_core

**Review by DeveloperMetal — DISMISSED** [review]

**Comment by DeveloperMetal** [comment]
@Alchez just following up on this, any reason this is still open?

**Comment by Alchez** [comment]
@forellana-digithinkit, yeah, we actually got a similar PR with only JSON changes rejected upstream since it had no controller changes, and "could be done via customizations instead".

So Nikhil is working on adding a dialog on DNs to record the reasons for rejection from the user for each item now.

**Comment by Alchez** [comment]
Made upstream to [develop](https://github.com/frappe/erpnext/pull/20829).

**Comment by DeveloperMetal** [comment]
@Alchez this PR is out of sync with upstream with conflicting changes.
You should update the PR to make it easier on them to merge if they get around to it

**Comment by Alchez** [comment]
@forellana-digithinkit, it was just a date conflict, I've fixed it upstream

**Review by Alchez — APPROVED** [review]

**Pull request merged**
