### PR TITLE
fix: made account numbers mandatory for chart of accounts

### PR DESCRIPTION
**Pull request by hitenshKharva**
Ref : [Asana Task](https://app.asana.com/0/1199082161983365/1199582655589330)

image

### CODE REVIEW

**Review by vishdha — COMMENTED** [review]
@hitenshKharva what is use case for this. if you make this madetorty then erpnext is not statble for all country. because not all user use numbers in coa, system should be compatible with both with numbers and with out number.

still,  if you want to go with this change then you have to make changes all place where it break like setup wizard contain india -chart of account and statndard chart account that need to fix

**Comment by hrwX** [comment]
@vishdha We need this for a feature @rvpasari has been building maybe he can give more context on that @rvpasari

**Comment by rvpasari** [comment]
> @vishdha We need this for a feature @rvpasari has been building maybe he can give more context on that @rvpasari

Thanks for refering this to me @hrwX. So I had raised the need to enforce account numbers in our system to Megan and Antoinette, given that they play a critical role in forming the accounts tree at the backend which is used for several things, including arranging the accounts in order in the financial statements. They agreed at the time that the best way forward would be to make account numbers mandatory for all users, even if they are dummy numbers and are not used internally by the company. Hence we made a task to execute this. If it will create issues in the system that are beyond repair, I'm sure Megan and Antoinette would understand why that change is not possible at this moment. 

On another note, @vishdha if you happen to know the places where enforcing account numbers could break, could you please help @hitenshKharva with this task?

**Comment by vishdha** [comment]
Closing this

**Comment by sahil28297** [comment]
@hitenshKharva @rvpasari @vishdha whats up with this task, there's been no activity here since it has been reopened.

**Comment by hrwX** [comment]
@rvpasari @hitenshKharva Closing this task, reopen only if the task is being actively developed

**Pull request closed without merging**
