### PR TITLE
fix: updated project table as per pervious task's project table

### PR DESCRIPTION
**Pull request by meshramsaroj**
**Task link:** https://bloomstack.com/desk#Form/Task/TASK-2021-00712

**GIF:**

dependent-task-project-table

### CODE REVIEW

**Comment by meshramsaroj** [comment]
checked with @Anurag810 regarding the depends_on child table issue.
As per discussion, it says framework issue.

**Comment by Anurag810** [comment]
@sahil28297 checked debugged with @meshramsaroj and observed that if DocType has a link field of the same DocType (like task having link field of task) then it does not fetch the value. the problem is in the `control/link.js` file. need to be handled saperately

**Comment by sahil28297** [comment]
> @sahil28297 checked debugged with @meshramsaroj and observed that if DocType has a link field of the same DocType (like task having link field of task) then it does not fetch the value. the problem is in the `control/link.js` file. need to be handled saperately

@Anurag810 @meshramsaroj Then that needs to be fixed as well, otherwise this PR will not work as intended. Please take this up if you get the time, otherwise close this PR.

**Comment by Anurag810** [comment]
@sahil28297 Told @MyuddinKhatri to work on this separately.
@MyuddinKhatri  any updates on this issue...
@meshramsaroj please reopen the PR once the issue is fixed.

**Pull request closed without merging**
