### PR TITLE
fix(selling): Fix return deliveries with credit notes

### PR DESCRIPTION
**Pull request by Alchez**
**Problem:**

When making sales returns while a Credit Note is issued, the system wasn't able to create a return invoice, and throws an error message of "All items have already been invoiced".

image

**Cause:**
The function that creates an invoice for a delivery only considered positive quantities in the items table (basically only sales receipts, and not sales returns).

### CODE REVIEW

**Comment by vjFaLk** [comment]
Upstream?

**Comment by Alchez** [comment]
Made upstream at https://github.com/frappe/erpnext/pull/17340.

**Comment by vjFaLk** [comment]
Make it to hotfix too bruh

**Comment by Alchez** [comment]
Made to hotfix at https://github.com/frappe/erpnext/pull/17341.

**Comment by Alchez** [comment]
Moved to #185.

**Pull request closed without merging**
