### PR TITLE
[v12] Update from upstream

### PR DESCRIPTION
**Pull request by Alchez**

### CODE REVIEW

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 2
           

Complexity increasing per file
==============================
- erpnext/assets/report/fixed_asset_register/fixed_asset_register.py  3
- erpnext/patches/v12_0/create_irs_1099_field_united_states.py  2
- erpnext/accounts/report/accounts_payable/accounts_payable.js  1
- erpnext/accounts/doctype/sales_invoice/sales_invoice.py  1
- erpnext/accounts/report/item_wise_purchase_register/item_wise_purchase_register.py  4
- erpnext/hr/utils.py  1
- erpnext/patches/v12_0/rename_bank_reconciliation_fields.py  2
- erpnext/accounts/report/accounts_receivable/accounts_receivable.js  1
         

Complexity decreasing per file
==============================
+ erpnext/healthcare/doctype/lab_test_template/lab_test_template.js  -1
+ erpnext/accounts/report/financial_statements.py  -1
+ erpnext/manufacturing/doctype/production_plan/production_plan.py  -1
+ erpnext/accounts/doctype/bank_reconciliation/bank_reconciliation.py  -1
         

Clones added
============
- erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py  2
- erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.js  1
- erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.js  3
- erpnext/accounts/report/item_wise_purchase_register/item_wise_purchase_register.js  2
- erpnext/public/js/controllers/transaction.js  1
- erpnext/accounts/report/accounts_payable/accounts_payable.js  2
- erpnext/accounts/report/item_wise_purchase_register/item_wise_purchase_register.py  2
- erpnext/accounts/report/cash_flow/cash_flow.js  1
- erpnext/accounts/report/accounts_receivable/accounts_receivable.js  2
         

Clones removed
==============
+ erpnext/healthcare/doctype/lab_test_template/lab_test_template.js  -1
+ erpnext/healthcare/doctype/lab_test_template/lab_test_template.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DigiThinkIT/erpnext/pullRequest?prid=5041592&bid=16602019)

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 2
           

Complexity increasing per file
==============================
- erpnext/accounts/report/accounts_receivable/accounts_receivable.js  1
- erpnext/assets/report/fixed_asset_register/fixed_asset_register.py  3
- erpnext/accounts/report/accounts_payable/accounts_payable.js  1
- erpnext/patches/v12_0/create_irs_1099_field_united_states.py  2
- erpnext/accounts/report/item_wise_purchase_register/item_wise_purchase_register.py  4
- erpnext/patches/v12_0/rename_bank_reconciliation_fields.py  2
- erpnext/hr/utils.py  1
- erpnext/accounts/doctype/sales_invoice/sales_invoice.py  1
         

Complexity decreasing per file
==============================
+ erpnext/manufacturing/doctype/production_plan/production_plan.py  -1
+ erpnext/accounts/doctype/bank_reconciliation/bank_reconciliation.py  -1
+ erpnext/accounts/report/financial_statements.py  -1
+ erpnext/healthcare/doctype/lab_test_template/lab_test_template.js  -1
         

Clones added
============
- erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.js  3
- erpnext/accounts/report/accounts_receivable/accounts_receivable.js  2
- erpnext/accounts/report/item_wise_purchase_register/item_wise_purchase_register.js  2
- erpnext/accounts/report/accounts_payable/accounts_payable.js  2
- erpnext/public/js/controllers/transaction.js  1
- erpnext/accounts/report/cash_flow/cash_flow.js  1
- erpnext/accounts/report/item_wise_purchase_register/item_wise_purchase_register.py  2
- erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py  2
- erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.js  1
         

Clones removed
==============
+ erpnext/healthcare/doctype/lab_test_template/lab_test_template.py  -1
+ erpnext/healthcare/doctype/lab_test_template/lab_test_template.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DigiThinkIT/erpnext/pullRequest?prid=5041592&bid=16602019)

**Comment by DeveloperMetal** [comment]
@Alchez see last comment on https://github.com/DigiThinkIT/frappe/pull/188

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 3
           

Complexity increasing per file
==============================
- erpnext/assets/report/fixed_asset_register/fixed_asset_register.py  3
- erpnext/patches/v12_0/rename_bank_reconciliation_fields.py  2
- erpnext/accounts/report/item_wise_purchase_register/item_wise_purchase_register.py  4
- erpnext/accounts/report/accounts_receivable/accounts_receivable.js  1
- erpnext/patches/v12_0/create_irs_1099_field_united_states.py  2
- erpnext/accounts/doctype/sales_invoice/sales_invoice.py  1
- erpnext/accounts/report/accounts_payable/accounts_payable.js  1
- erpnext/hr/utils.py  1
         

Complexity decreasing per file
==============================
+ erpnext/healthcare/doctype/lab_test_template/lab_test_template.js  -1
+ erpnext/accounts/report/financial_statements.py  -1
+ erpnext/accounts/doctype/bank_reconciliation/bank_reconciliation.py  -1
+ erpnext/manufacturing/doctype/production_plan/production_plan.py  -1
         

Clones added
============
- erpnext/accounts/report/cash_flow/cash_flow.js  1
- erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.py  2
- erpnext/accounts/report/item_wise_purchase_register/item_wise_purchase_register.py  2
- erpnext/accounts/report/accounts_receivable/accounts_receivable.js  2
- erpnext/accounts/report/item_wise_purchase_register/item_wise_purchase_register.js  2
- erpnext/accounts/report/item_wise_sales_register/item_wise_sales_register.js  3
- erpnext/accounts/report/accounts_payable/accounts_payable.js  2
- erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.js  1
- erpnext/public/js/controllers/transaction.js  1
         

Clones removed
==============
+ erpnext/healthcare/doctype/lab_test_template/lab_test_template.py  -1
+ erpnext/healthcare/doctype/lab_test_template/lab_test_template.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DigiThinkIT/erpnext/pullRequest?prid=5041592&bid=16602019)

**Pull request merged**
