### PR TITLE
feat(attendance): add work from home option in status

### PR DESCRIPTION
**Pull request by Alchez**
Frontport from #276.

### CODE REVIEW

**Comment by vjFaLk** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- erpnext/hr/doctype/attendance/attendance_list.js  2
         

Clones added
============
- erpnext/hr/doctype/employee_attendance_tool/employee_attendance_tool.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DigiThinkIT/erpnext/pullRequest?prid=4897321&bid=16217807)

**Review by neilLasrado — APPROVED** [review]

**Comment by neilLasrado** [comment]
@Alchez have you also sent this PR upstream?

**Comment by Alchez** [comment]
Not yet, I'll make it to `develop`.

**Comment by Alchez** [comment]
Made upstream to [develop](https://github.com/frappe/erpnext/pull/20464).

**Pull request merged**
