### PR TITLE
fix warehouse name change issue

### PR DESCRIPTION
**Pull request by rvpasari**
**Ref:** [Asana](https://app.asana.com/0/1188592895233593/1195067417536933)

### CODE REVIEW

**Comment by Alchez** [comment]
I don't think this is a valid fix, the company should not be edited while creating the warehouse. It should instead be picking up the right company.

@rvpasari Check what could be causing that

**Review by neilLasrado — CHANGES_REQUESTED** [review]
The company should not be editable in the warehouse, it can cause more issues with Accounting etc

**Comment by rvpasari** [comment]
Yeah this is an old PR, @nmimsnikhil is handling the task I believe now

**Comment by hrwX** [comment]
@rvpasari Does this PR fixes the warehouse issue ?

**Comment by rvpasari** [comment]
No sir, unfortunately it doesn't. We can't allow the user to change the name of the company while creating a warehouse, as Rohan and Neil have commented. It has to pick the right name when one selects the add child option.

**Comment by hrwX** [comment]
@rvpasari can you post a gif for this

**Comment by hrwX** [comment]
@rvpasari Closing this issue since @nmimsnikhil has fixed it.

**Pull request closed without merging**
