### PR TITLE
feat: Create new item on Bloomtrace from bloomstack

### PR DESCRIPTION
**Pull request by harshmule-epi**
**Task: To Create an Item from Bloomstack to Bloomtrace.**

### CODE REVIEW

**Comment by sahil28297** [comment]
@harshmule-git Is this PR for testing Purpose or is this ready for review? In the later case, there are a lot of things to be changed.

**Comment by harshmule-epi** [comment]
> @harshmule-git Is this PR for testing Purpose or is this ready for review? In the later case, there are a lot of things to be changed.

Yes it's for review 
but yeah you can say it as for testing purpose because some of the things are hardcoded in the request json, which is just for testing purpose for now, will need to update once the whole resources are together.

**Comment by sahil28297** [comment]
If thats the case, Is it necessary to merge this? can you just push it to your remote and checkout the branch on the test server to your remote branch. It is not ideal to merge hard-coded things to main branch.

**Comment by harshmule-epi** [comment]
Closing the PR, will create a new PR for item changes for bloomtrace!

**Pull request closed without merging**
