### PR TITLE
feat: update strain doctype with new bloomtrace architecture

### PR DESCRIPTION
**Pull request by harshmule-epi**
> [Task ID](https://bloomstack.com/desk#Form/Task/TASK-2021-00242)

> **Description: Update Strain Doctype for the new architecture**
    
Post data to bloomtrace from bloomstack strain doctype through bloomtrace API.

### CODE REVIEW

**Comment by sahil28297** [comment]
@harshmule-git Is this PR for testing Purpose or is this ready for review? In the later case, there are a lot of things to be changed.

**Comment by harshmule-epi** [comment]
> @harshmule-git Is this PR for testing Purpose or is this ready for review? In the later case, there are a lot of things to be changed.

Yes it's for review!
but yeah you can say it as for testing purpose because some of the things are hardcoded in the request_data json, which is just for testing purpose for now, will need to update once the whole resources are together.

**Comment by sahil28297** [comment]
If thats the case, Is it necessary to merge this? can you just push it to your remote and checkout the branch on the test server to your remote branch. It is not ideal to merge hard-coded things to main branch.

**Comment by harshmule-epi** [comment]
> If thats the case, Is it necessary to merge this? can you just push it to your remote and checkout the branch on the test server to your remote branch. It is not ideal to merge hard-coded things to main branch.

sure, will do that!!
but there are multiple PR in different branches , how i can manage that within same branch?

**Comment by harshmule-epi** [comment]
Will be creating new PR for this task and closing this one, as new changes are implemented in the strain, and also wan't to get rid of unnecessary commits (merge commits).

**Pull request closed without merging**
